### ISSUE TITLE
Set Up Prettier and ESLint

### ISSUE THREAD

**Issue by RO-HSA** [Super-Patos-Hackaton/frontend#12]
## Description
Configure Prettier and ESLint to maintain code consistency and quality across the project.

https://dev.to/jsdevspace/setup-nextjs-14-project-with-eslint-prettier-tailwind-css-226j

## Motivation
To enforce a consistent coding style and catch potential errors early, we need to integrate Prettier and ESLint into our development workflow. This will help ensure that all code address to the same standards and improve overall code quality.

## Tasks
- [x] Install Prettier as development dependencies
- [x] Set up Prettier configuration file (.prettierrc)
- [x] Set up ESLint configuration file (.eslintrc.json)
- [x] Set up ignore files (.prettierignore / .eslintignore)
- [x] Integrate Prettier with ESLint
- [x] Configure ESLint rules based on project requirements
- [x] Configure and integrate pre-commit hooks with Husky, Commitlint and lint-staged
- [x] Document the Prettier and ESLint setup and usage guidelines in the project's README
